<a href="https://colab.research.google.com/github/MiguelAngel-ht/PyTorch-Examples/blob/main/01Nb-Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch (Basics)**

**PyTorch** is an optimized tensor library for deep learning using GPUs and CPUs.

**Torch** is an open-source machine learning library, a scientific computing framework, and a script language based on the Lua programming language.

In [1]:
import torch

In [2]:
# define a number
t = torch.tensor(5.0)
t

tensor(5.)

In [7]:
# type variable
t.dtype

torch.float32

In [8]:
# vector
v = torch.tensor([1,2,3,4])
v

tensor([1, 2, 3, 4])

In [10]:
# matrix
m = torch.tensor([[1,2,3,4],[1,2,3,4]])
m

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4]])

In [11]:
# 3 dimentional array
t1 = torch.tensor([[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4]]])
t1

tensor([[[1, 2, 3, 4],
         [1, 2, 3, 4]],

        [[1, 2, 3, 4],
         [1, 2, 3, 4]]])

In [12]:
# shapes
print('number: ', t.shape)
print('vector: ', v.shape)
print('matrix: ', m.shape)
print('tensor: ', t1.shape)

number:  torch.Size([])
vector:  torch.Size([4])
matrix:  torch.Size([2, 4])
tensor:  torch.Size([2, 2, 4])


In [2]:
# create tensor
x = torch.tensor(3.)
b = torch.tensor(4., requires_grad=True)
w = torch.tensor(5., requires_grad=True)

In [3]:
# arithmetic operation 
y = x * w   +   b
y

tensor(19., grad_fn=<AddBackward0>)

$y = 3x + 4$

In [4]:
# compute derivative
y.backward()

In [5]:
# gradiants
print('dy/dx =', x.grad)
print('dy/dw =', w.grad)
print('dy/db =', b.grad)

dy/dx = None
dy/dw = tensor(3.)
dy/db = tensor(1.)


Using Numpy 

In [6]:
import numpy as np

In [9]:
# array
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [10]:
# convert numpy array to torch tersor
y = torch.from_numpy(v)
y 

tensor([1, 2, 3, 4])

In [11]:
# convert torch tersor to numpy array
x = y.numpy()
x 

array([1, 2, 3, 4])