<a href="https://colab.research.google.com/github/MiguelAngel-ht/PyTorch-Examples/blob/main/02_Linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Regression

with Torch

In [1]:
import numpy as np
import torch as tr

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
# Convert inputs and targets to tensors
inputs = tr.from_numpy(inputs)
targets = tr.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
# Weights and biases
w = tr.randn(2, 3, requires_grad=True)
b = tr.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.1910,  0.3725, -1.9974],
        [ 0.2930, -0.1496, -0.2991]], requires_grad=True)
tensor([-0.4086, -0.7752], requires_grad=True)


**Model**

$y = X × W^T + b$

In [6]:
# @ is a matrix multiplication and .t() method is the transpose
def model(x):
    return x @ w.t() + b

In [7]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ -75.2782,   -2.2670],
        [-112.8379,   -6.4144],
        [ -82.9550,  -12.6719],
        [ -77.7714,   11.6142],
        [-117.6413,  -15.8514]], grad_fn=<AddBackward0>)


In [8]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return tr.sum(diff * diff) / diff.numel() # diff.numel() is the number of elements

In [10]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(21103.9805, grad_fn=<DivBackward0>)


In [11]:
# Compute gradients
loss.backward()

In [12]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-0.1910,  0.3725, -1.9974],
        [ 0.2930, -0.1496, -0.2991]], requires_grad=True)
tensor([[-14038.7129, -15677.4131,  -9780.0811],
        [ -7923.5518,  -9570.3438,  -5761.9697]])


In [13]:
w
w.grad

tensor([[-14038.7129, -15677.4131,  -9780.0811],
        [ -7923.5518,  -9570.3438,  -5761.9697]])

In [15]:
with tr.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [16]:
# Let's verify that the loss is actually lower
loss = mse(preds, targets)
print(loss)

tensor(21103.9805, grad_fn=<DivBackward0>)


In [17]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


Train the model using gradient descent

In [18]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[-50.3189,  12.4080],
        [-80.0056,  12.9066],
        [-44.0594,  10.3887],
        [-53.0903,  25.9444],
        [-86.0565,   2.8377]], grad_fn=<AddBackward0>)


In [19]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(14492.2520, grad_fn=<DivBackward0>)


In [20]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-11460.6133, -12904.0254,  -8069.1621],
        [ -6406.1548,  -7933.5537,  -4753.2617]])
tensor([-138.9061,  -79.1029])


In [22]:
# Adjust weights & reset gradients
with tr.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [23]:
print(w)
print(b)

tensor([[ 0.0640,  0.6583, -1.8189],
        [ 0.4363,  0.0255, -0.1939]], requires_grad=True)
tensor([-0.4055, -0.7735], requires_grad=True)


In [24]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(10034.2900, grad_fn=<DivBackward0>)


Train for multiple epochs

In [25]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with tr.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [26]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(392.7098, grad_fn=<DivBackward0>)


In [27]:
# Predictions
preds

tensor([[ 61.5825,  75.5952],
        [ 70.0286,  98.8850],
        [139.2875, 128.5179],
        [ 45.6171,  67.9501],
        [ 66.3372,  97.8275]], grad_fn=<AddBackward0>)

In [28]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

# Linear regression using PyTorch built-ins

In [29]:
import torch.nn as nn

In [30]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = tr.from_numpy(inputs)
targets = tr.from_numpy(targets)

In [31]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [32]:
from torch.utils.data import TensorDataset

In [33]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [34]:
from torch.utils.data import DataLoader

In [35]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [36]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [ 68.,  97.,  70.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.]])
tensor([[103., 119.],
        [119., 133.],
        [102., 120.],
        [ 82., 100.],
        [118., 134.]])


In [37]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.0135,  0.5624, -0.3689],
        [ 0.5648, -0.4989,  0.3968]], requires_grad=True)
Parameter containing:
tensor([-0.4477, -0.3343], requires_grad=True)


In [38]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.0135,  0.5624, -0.3689],
         [ 0.5648, -0.4989,  0.3968]], requires_grad=True),
 Parameter containing:
 tensor([-0.4477, -0.3343], requires_grad=True)]

In [39]:
# Generate predictions
preds = model(inputs)
preds

tensor([[22.3549, 24.5291],
        [26.6617, 32.5504],
        [54.6917,  4.9615],
        [11.4604, 50.5001],
        [28.6519, 18.5150],
        [21.8060, 25.5927],
        [25.7304, 33.4460],
        [54.3363,  5.9230],
        [12.0093, 49.4364],
        [28.2696, 18.3470],
        [21.4237, 25.4247],
        [26.1127, 33.6140],
        [55.6229,  4.0658],
        [11.8427, 50.6681],
        [29.2009, 17.4513]], grad_fn=<AddmmBackward0>)

In [40]:
# Import nn.functional
import torch.nn.functional as F

In [41]:
# Define loss function
loss_fn = F.mse_loss

In [42]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(4713.0171, grad_fn=<MseLossBackward0>)


Instead of manually manipulating the model's weights & biases using gradients, we can use the optimizer.

In [44]:
# Define optimizer
opt = tr.optim.SGD(model.parameters(), lr=1e-5)

In [45]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [46]:
fit(120, model, loss_fn, opt, train_dl)

Epoch [10/120], Loss: 247.3057
Epoch [20/120], Loss: 443.9304
Epoch [30/120], Loss: 505.8626
Epoch [40/120], Loss: 325.9683
Epoch [50/120], Loss: 173.3571
Epoch [60/120], Loss: 150.0960
Epoch [70/120], Loss: 100.6793
Epoch [80/120], Loss: 92.5820
Epoch [90/120], Loss: 77.0184
Epoch [100/120], Loss: 70.1039
Epoch [110/120], Loss: 35.7971
Epoch [120/120], Loss: 38.4850


In [47]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 57.9742,  71.6996],
        [ 78.0226, 100.8380],
        [126.5173, 130.6771],
        [ 26.0512,  45.0809],
        [ 91.6811, 114.6319],
        [ 56.7117,  70.8153],
        [ 77.0666, 100.8773],
        [126.3938, 131.3064],
        [ 27.3137,  45.9652],
        [ 91.9876, 115.5556],
        [ 57.0182,  71.7390],
        [ 76.7602,  99.9536],
        [127.4733, 130.6377],
        [ 25.7448,  44.1572],
        [ 92.9436, 115.5163]], grad_fn=<AddmmBackward0>)

In [48]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [50]:
model(tr.tensor([[75, 63, 44.]]))

tensor([[53.4458, 69.2332]], grad_fn=<AddmmBackward0>)